### ISSUE TITLE
Would you be interested in "modernizing"

### ISSUE THREAD

**Issue by mrallen1** [AdRoll/kinetic#18]
I'd like to shave this yak by moving to a rebar3 build and using maps as the internal data representation for JSON.  Is there any appetite on your part to merge in PRs toward that end?  Thanks!

**Comment by zerth** [comment]
Sounds like a worthy effort, although we have an internal system lingering on rebar2 and so would need to keep rebar2 compatibility or maintain a separate rebar2-compatible branch until it can be migrated.

**Comment by elbrujohalcon** [comment]
This is already done.
